### PR TITLE
chore: tweak deserialize error message

### PR DESCRIPTION
**Pull request by quake**

### CODE REVIEW

**Comment by yangby-cryptape** [comment]
Thanks, very much!

And, forgive my greed: can you provide property tests?

Here is an example:

https://github.com/yangby-cryptape/rust-numext/blob/f737ee647f5a56258209d8b61a0d3aafc22b4dbf/fixed-hash-tests/tests/std_str.rs#L16-L29

**Comment by doitian** [comment]
@yangby-cryptape #21 does not include this, which checks prefix 0x before checking the length.

**Comment by yangby-cryptape** [comment]
Oh, my mistake!
It was a bit late when I merged #21 and close this PR last night, I am a little dizzy at that time~
Sorry for that.

**Comment by quake** [comment]
@yangby-cryptape rebased with dev branch, regarding the test, can't use property tests for error message testing, please help to review this PR, thanks.

**Pull request merged**
